// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yibrrjblxuoebnecbntp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpYnJyamJseHVvZWJuZWNibnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTg2NzksImV4cCI6MjA2NTM3NDY3OX0.fl0Z5vt9wT4BwcGdIm-VW4Pm6AxjxYsNBm2TB2oP4tU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);